### ISSUE TITLE
Ensembles on multiple attributes?

### ISSUE THREAD

**Issue by jservonnat** [senesis/climaf#100]
Today, we can easily build an ensemble over multiple values of one attribute using cdataset.explore('ensemble').
It would definitely be interesting to build ensembles over multiple attributes: model and realization, institute, driving_model and model (for CORDEX/RCM projects).
One issue is the naming of the member; an answer is that we name the members with the value of each attribute (for the member), separated with '_' (or a user-provided separator?).
Example: CNRM-CM5_r1i1p1

The behaviour of explore('ensemble') could be:
- cdataset.explore('ensemble') returns an error if more than one attribute has multiple values; and also returns the list of those attributes
- cdataset.explore('ensemble', build_ensemble_on=['model','realization']) forces to build the ensemble on the multiple values of model and realization and names the members with model_realization; returns a similar error as above if not only the attributes provided to build_ensemble_on (here model and realization) have multiple values)

**Comment by senesis** [comment]
Re. first case : cannot both raise an error and return a value
Otherwise : quite clear

**Comment by jservonnat** [comment]
Sorry, wrong sentence:
raise and error and **print** the list of attributes with multiple values (with the values?)

**Comment by senesis** [comment]
implemented in V1.2.9, but does not raise errors in first case; andwithout arg build_on_ensemble; but arg 'first' allow to tell which attribute is the prefix for labels
