### ISSUE TITLE
Tag the results in the cache for a controlled cleaning

### ISSUE THREAD

**Issue by jservonnat** [senesis/climaf#105]
In addition to the available possibilities to clean the cache (pattern, age, size), it would be very useful to be able to tag the results in the cache to have the possibility to clean all the results but those ones.
I imagine that we could emphasize a solution with a tag on the CRS, but the real smart solution might not be that simple.

I think it is a really important point because:
- the number of climaf users will surely increase (notably on Ciclad/Climserv)
- as well as the size (in resolution, and ensemble analysis) of the data stored in the cache
- and the parallel processing of ensembles (#24) implies a csync(True) that will be significantly slowed down with a heavily loaded cache (number of results)

I assume that this way to clean the cache will be much more drastic (and also more meaningful from the user responsability of the content of the cache) in terms of cache cleaning.

Behaviour:
- we want to pass a command in one simple line to clean everything but the tagged results
- cdrop and crm() should allow removing a tagged result (with an option, like cdrop(obj, force=True))
- craz() keeps the same behaviour

**Comment by senesis** [comment]
On the implementation side : let us assume that all cache files are owned by a single user which has umask 022. CliMAF could implement tagging by suppressing write permission; this would allow the 'tagger' CliMAF instance to 'communicate' to other CliMAF instances (running in parallel) the tagged status of the object. CliMAF would erase such write-protected objects by restoring the write permission when arg force=True is used (or craz is used); a new 'cclean' command could do a craz except on tagged obects

**Comment by jservonnat** [comment]
That sounds just fine!

**Comment by senesis** [comment]
solved with version 1.2.9 - see function cprotect()
