### ISSUE TITLE
How to report errors in the documentation?

### ISSUE THREAD

**Issue by jypeter** [senesis/climaf#122]
I have seen 2 typos when having a quick look at the documentation and I have not found an obvious way to report errors about the documentation, in the documentation. I have looked at:
- [Community & Contact](https://climaf.readthedocs.io/en/master/community.html)
- [contribute to improve CliMAF documentation](https://climaf.readthedocs.io/en/master/howto.html#how-to-contribute-a-script)

So I'm using [report an issue](https://climaf.readthedocs.io/en/master/howto.html#report-an-issue)

Maybe someone can add "howto... report errors in the doc" somewhere

And the 2 minor (but amusing) errors are:
- Page [Installing, configuring, using](https://climaf.readthedocs.io/en/master/installing.html?highlight=eventually): **eventually, use**. Do you mean _finally_, or _possibly_?
- Page [Requirements and ackowledgements](https://climaf.readthedocs.io/en/master/requirements.html#requirements): I guess _unvaluable contribution_  should be _invaluable contribution_ . You probably also want to use _ack**N**owledgements_. And I'm not sure the bottom of the page _If wanting to build or modify CliMAF documentation_ belongs here

I can try to report errors (more briefly than here!), but unfortunately I don't think I'll take time to build the documentation and change its sources :-)

**Comment by senesis** [comment]
Thanks for having scrutinized the doc, both for errors and for the finding the best way to report it
Using 'issues' as a method for reporting doc errors is fine, as we are not really expecting all users to go through the steps described at [contribute to improve CliMAF documentation](https://climaf.readthedocs.io/en/master/howto.html#how-to-contribute-a-script)

[According to some sources,](https://www.thesaurus.com/browse/eventually) "eventually" actually is a synonym for "finally", but I agree this can be misleading for french users; [finally](https://www.thesaurus.com/browse/finally) has first-rank synonyms which are inappropriate, so maybe [lastly](https://www.thesaurus.com/browse/lastly) would be the best choice ?

Thanks for pinpointing the typo on invaluable and on extra text nearby

**Comment by senesis** [comment]
fixed with commit 75d6f0b
