### ISSUE TITLE
'unexpected success' of test_9_cdo

### ISSUE THREAD

**Issue by jypeter** [senesis/climaf#128]
I have run `testing/test_install.sh` at LSCE and on ciclad (in my custom CDAT installation) and the result of test_9_cdo is amusing, but a bit surprising. Should it just be **ok**?

```
test_7_cdo (test_req.A_externals) ... ok
test_9_cdo (test_req.A_externals) ... unexpected success

```

**Comment by senesis** [comment]
Actually, this is a test that ncview is available, and this is actually non-blocking. It should read 'success for a non-mandatory requirement'
But most users didn't bother, yet.
