### ISSUE TITLE
Need for more basic functions in module html

### ISSUE THREAD

**Issue by senesis** [senesis/climaf#42]
Function html_table_line(s) are fine for tables. There is however a need for a more basic function, which would take two arguments : a CliMAF object of type figure and a label, and which would return the html code for a link from that label to the Climaf cache file for the figure

**Comment by jservonnat** [comment]
Suggestions for the form of html_table_line from the user side (with p1, p2, px being climaf objects of type figure):
- html_table_line( { 'My figure p1' : p1,    'My figure p2' : p2,    'My figure px' : px})
Then html_table_line would loop on the elements of the dictionary. The facets will be used as titles and the values are the plots.
Or:
- html_table_line( plots=[p1, p2, px], titles=[ 'My figure p1', 'My figure p2', 'My figure px' ] )

The first form is more compact and pretty logical in a way. The second form is more basic, maybe more readable. Please give your comments!

**Comment by senesis** [comment]
I would vote for first form. This would lead to rename the present function html_table_line to something like 'html_table_line_with_func' (because it is calling some function iteratively for computing figures).
Alos : the new html_table_line should allow for a 'thumbnail' argument, in which case the dict argument could be a list (because titles would be replaced by thumbnail images)

**Comment by mpmoine** [comment]
Form 1 suggested by Jerome sounds the best to me too. 

But I would keep "html rendering" and "plot creation" as separated operations. Thus, I would advocate  in favor of removing plot creation step (call to a function) from html_table_lines.

 Intuitively user comptes his diags, creates associated plot objects first and call for an html rendering in a second step. Moreover he may want to draw different types of plot (time serie, map, slice) on a same line that would not be possible with a "create_plot" function embedded within html_tables_lines (or this woud require to pass an additionnal dictionary in arguments with the list of plot types).

**Comment by senesis** [comment]
Agree. Suggestions implemented in V0.10
