### ISSUE TITLE
Latitude and longitude names in gplot.ncl

### ISSUE THREAD

**Issue by jservonnat** [senesis/climaf#47]
We have to find a way so that the script gplot.ncl is less sensitive to the name of the dimensions, notably for the spatial dimensions 'lat' and 'lon'. At the moment, if the input file has dimensions called 'LON' and 'LAT', the script returns an error.
```
fatal:["Execute.c":5861]:variable (lat) is not in file (ffile)
```

**Comment by LudivineV** [comment]
Done in version 0.12
