### ISSUE TITLE
Problem converting to CliMAF object to MA

### ISSUE THREAD

**Issue by jservonnat** [senesis/climaf#6]
I've been working with on the possibility to mix CDAT and CliMAF. But for the moment I have difficulties to convert a CliMAF object to a MA:
```
jservon@ciclad-ng:~/Evaluation/CliMAF> python
Python 2.7.4 (default, Apr 22 2014, 14:55:23)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> from climaf.api import *
Cache set to /data/jservon/climaf_cache
>>> cdef('project','CMIP5')
>>> cdef('experiment','historical')
>>> cdef('frequency','monthly')
>>> dataloc(organization="CMIP5_DRS",url=['/prodigfs/esg/'])
<climaf.dataloc.dataloc instance at 0x7f47c10a1c68>
>>> dat=ds(model='IPSL-CM5A-LR',
...        rip='r1i1p1',
...        variable='tas',
...        period='1980-2000',
...        )
>>> dat.baseFiles()
'/prodigfs/esg/CMIP5/merge/IPSL/IPSL-CM5A-LR/historical/mon/atmos/Amon/r1i1p1/v20110406/tas/tas_Amon_IPSL-CM5A-LR_historical_r1i1p1_185001-200512.nc'
>>> test = cMA(dat)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssenesi/climaf/climaf/api.py", line 160, in cMA
    return climaf.driver.ceval(obj,format='MaskedArray',deep=deep)
  File "/home/ssenesi/climaf/climaf/driver.py", line 180, in ceval
    rep=ceval(extract,userflags=userflags,format=format,deep=deep,recurse_list=recurse_list)
  File "/home/ssenesi/climaf/climaf/driver.py", line 267, in ceval
    return cread(file)
  File "/home/ssenesi/climaf/climaf/driver.py", line 545, in cread
    if varname is None: varname=varOfFile(datafile)
  File "/home/ssenesi/climaf/climaf/netcdfbasics.py", line 14, in varOfFile
    if (filevar not in fileobj.dimensions) and not re.findall("^time_",filevar) :
NameError: global name 're' is not defined
>>>
```
@senesis any thought?

**Comment by senesis** [comment]
At some stage , an 'import re' was missing in netcdf_bascis.py. I think that it is fixed in HEAD of master branch, now. You can either 'git pull' or change your code manually. Before pulling, please note that version 0.6.0 is about to come (maybe today...)

**Comment by senesis** [comment]
Jérome 

Je t'ai répondu via GitHub sur le détail. Mais, sur le fond : je suis inquiet que tu te jettes sur les Masked Array, parce qu'il n'existe pas encore la possibilité d'alimenter des opérateurs CliMAF par des objets de ce type (et seulement l'inverse : CliMAF produit du Masked Array); du coup, tu vas te hâter de te passer des opérateurs CliMAF, du cache CliMAF .... 

Donc, OK pour tester des fonctionnaltés, mais garde ça à l'esprit 

S 

----- Mail original -----

| De: "jservonnat" <notifications@github.com>
| À: "senesis/climaf" <climaf@noreply.github.com>
| Cc: "Stéphane Sénési - work" <stephane.senesi@meteo.fr>
| Envoyé: Jeudi 23 Avril 2015 14:33:34
| Objet: [climaf] Problem converting to CliMAF object to MA (#6)

| I've been working with on the possibility to mix CDAT and CliMAF. But for the
| moment I have difficulties to convert a CliMAF object to a MA:
| jservon@ciclad-ng:~/Evaluation/CliMAF> python
| Python 2.7.4 (default, Apr 22 2014, 14:55:23)
| [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
| Type "help", "copyright", "credits" or "license" for more information.
| >>> import numpy
| >>> from climaf.api import *
| Cache set to /data/jservon/climaf_cache
| >>> cdef('project','CMIP5')
| >>> cdef('experiment','historical')
| >>> cdef('frequency','monthly')
| >>> dataloc(organization="CMIP5_DRS",url=['/prodigfs/esg/'])
| <climaf.dataloc.dataloc instance at 0x7f47c10a1c68>
| >>> dat=ds(model='IPSL-CM5A-LR',
| ...        rip='r1i1p1',
| ...        variable='tas',
| ...        period='1980-2000',
| ...        )
| >>> dat.baseFiles()
| '/prodigfs/esg/CMIP5/merge/IPSL/IPSL-CM5A-LR/historical/mon/atmos/Amon/r1i1p1/v20110406/tas/tas_Amon_IPSL-CM5A-LR_historical_r1i1p1_185001-200512.nc'
| >>> test = cMA(dat)
| Traceback (most recent call last):
| File "<stdin>", line 1, in <module>
| File "/home/ssenesi/climaf/climaf/api.py", line 160, in cMA
| return climaf.driver.ceval(obj,format='MaskedArray',deep=deep)
| File "/home/ssenesi/climaf/climaf/driver.py", line 180, in ceval
| rep=ceval(extract,userflags=userflags,format=format,deep=deep,recurse_list=recurse_list)
| File "/home/ssenesi/climaf/climaf/driver.py", line 267, in ceval
| return cread(file)
| File "/home/ssenesi/climaf/climaf/driver.py", line 545, in cread
| if varname is None: varname=varOfFile(datafile)
| File "/home/ssenesi/climaf/climaf/netcdfbasics.py", line 14, in varOfFile
| if (filevar not in fileobj.dimensions) and not re.findall("^time_",filevar) :
| NameError: global name 're' is not defined
| >>>

| @senesis any thought?

| —
| Reply to this email directly or view it on GitHub .

-- 
----- Météo-France ----- 
SENESI STEPHANE 
CNRM/GMGEC/ASTER 
stephane.senesi@meteo.fr 
Fixe : +33 561079931

**Comment by jservonnat** [comment]
Ok je n'avais pas vu cela. A la base c'était pour faire une soustraction entre deux champs pour faire une carte de biais, ce qui était une occasion d'essayer le regridding. Mais je peux aussi le faire avec cdo.
Je voulais aussi voir la compatibilité d'utilisation de climaf et de nos installations de CDAT comme nous en avions parlé.
Bref, je peux me retenir et ne pas me jeter sur les MA dans les immédiat ;).
