### ISSUE TITLE
Automatic cache management

### ISSUE THREAD

**Issue by jservonnat** [senesis/climaf#75]
When the cache becomes heavily loaded with results, the time spent scanning the index can be of the same order than the time spent to actually compute the result (especially in the context of the production of big atlases).

Here are some ideas to implement an automatic smart cache management (applied at the end of a CliMAF routine script for instance).

Each time we do a cfile (only when it leads to a new result), we keep:
- the time spent by CliMAF to scan the index
- the time spent to obtain the result

Using this information, we could clean the cache (say, with user-provided instructions at the end of the CliMAF script) by removing:
- the files that have a longer 'search time' than 'execution time'
- the files that have a longer 'search time' than a user-provided threshold (say, 1s)

We could also say that we don't want to have more than XX files in the cache (use of the disks), so we keep the XX files that have the longest 'execution time' and remove all the others.

**Comment by senesis** [comment]
What is the latest software version for which the issue is obvious ?
Should the 'time spent to obtain the result' be limited to cases where no sub-expression value was found in cache ?

**Comment by jservonnat** [comment]
We have been using 1.0.3 a lot for the development of IPSLCM6. I think we have reached a point where we produce too many intermediate files and load the disks in an unnecessary manner (issues with the quota).
When we execute a CliMAF atlas interactively (on a dedicated node) we have experienced many times that it spends a lot of time on processes like 'Searching for...'. If we totally erase the cache, the execution of the atlas is faster (from submission to result). If we resubmit the same atlas, CliMAF really takes advantage of the existing result and returns the atlas faster.
Maybe we have other issues that are coming from Ciclad and we need more investigations. I will come back at you with more details.

Concerning your second point... it is a good question :). I will provide my answer as soon as possible.

**Comment by senesis** [comment]
It would be interesting to record what is the files number in cache when the search time duration issue is noteworthy

**Comment by jservonnat** [comment]
Indeed. I'm actually working on it, and will provide more objective measures soon.

**Comment by senesis** [comment]
J.Polcher (tranlsated usind deepl.com) 
Why not add an "olderthan" option in craz ()? This can use a call to the find UNIX function! So the user can
put a call in all its scripts: craz (olderthan="1week") to grade only the part of the cache that is less than a week old. We can even make it "script sensitive". So it only clears the cache of the script in question. So if you have a quick cycle script (which doesn' t keeps its cache only one day) you don't destroy the script cache which wants to keep its outputs for a whole month.

Translated with www.DeepL.com/Translator

**Comment by jservonnat** [comment]
I've done some testing from a notebook, using my biggest cache (in terms of number of results).
I've tested different sequences of operations, with and without removing the result from the cache before computation (if it already was in there).
The results show excellent performance of the cache... around 1s to execute an operation if the result is not in the cache, and around 0.001s if it already there.
That tells me that the problem might not come from CliMAF when it reads the cache. I've had this issue of a 'slow cache' at different occasions (using the C-ESM-EP or CliMAF directly from a notebook).
I will setup a test to address that and try to identify where the problem comes from.
And will reopen the issue only when I have clearly isolated the problem.

**Comment by jservonnat** [comment]
Concerning Jan's comment, we can actually already do it with:
crm(age='+15')
if we want to remove the files older than 15 days.
I actually didn't see that we can use the pattern 'access' to remove the files that have not been accessed for n days... and will try it.
