### ISSUE TITLE
Make used data archive configurable

### ISSUE THREAD

**Issue by cehbrecht** [senesis/climaf#78]
Currently one has to edit the Python module `site_settings.py` to change or add the data archive used by climaf. It would be nice if the data archive could be configured.

**Comment by senesis** [comment]
Actually, easiness in configuring archive location is one of the basics of CliMAF. 

When wishing to access e.g. CMIP5 data at your own root location, you do not need to hack the code, and you can just use 

`dataloc(project="CMIP5", organization="CMIP5_DRS", url=[''my_own_root'')`

which can be either in your first commands or inserted in your own CliMAF setup file `~/.climaf`
For many cases, `organization=generic` is a good solution (it is the default)

**Comment by cehbrecht** [comment]
@senesis thanks ... it works.

**Comment by senesis** [comment]
I can anyway merge your changes which set 'atDKRZ', for the benefit of DKRZ users (provided the criterion you used is robust enough)

**Comment by cehbrecht** [comment]
I only added `atDKRZ` to get it work ... but the path is not stable enough.
