### ISSUE TITLE
Outputs and logs written to current directory

### ISSUE THREAD

**Issue by cehbrecht** [senesis/climaf#85]
I'm using climaf in a web processing service and the climaf executable is started in directory where it might not have write permission (using an unprivileged service user). Climafs writes log files (and probably more) to the current directory ... this fails in my service use case.

Output path with expected write permission should be made configurable (`logs/`, `temp/`, `outputs/`, ...).

**Comment by senesis** [comment]
Right. You can expect a fix before next week

**Comment by senesis** [comment]
Solved - branch master, commit 3e1762e - Uses environment variable CLIMAF_LOG_DIR

**Comment by cehbrecht** [comment]
@senesis thanks ... works for me.
