### ISSUE TITLE
mktemp creates dir in current folder

### ISSUE THREAD

**Issue by cehbrecht** [senesis/climaf#86]
I run into an issue with temp folders in `mcdo.sh`:

https://github.com/senesis/climaf/blob/3e1762ec788674b470d895b15aa398184c77bb4a/scripts/mcdo.sh#L25

It creates the temp folder in the current folder which might be write protected. The following patch worked for me:

```
$ mktemp -t climaf_mcdo -d
OR
$ mktemp -d /tmp/climaf_mcdo_XXXXXX
```

See also #85.

**Comment by senesis** [comment]
Implemented. Available in version 1.2.9 as 
tmp=$(mktemp -d -t climaf_mcdo_XXXXXX) # Will use TMPDIR if set, else /tmp
# Option -t/--tmpdir is not available at all sites -> test result
[ $? -ne 0 ] && tmp=$(mktemp -d  climaf_mcdo_XXXXXX)
